controller:

  JCasC:
    configScripts:

      kubernetes-cloud: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"

                serverUrl: "https://kubernetes.default.svc"

                namespace: "default"

                jenkinsUrl: "http://myjenkins.default.svc.cluster.local:8080"

                containerCapStr: "10"

                templates:
                  - name: "tools"
                    namespace: "default"
                    label: "tools"

                    containers:
                      - name: "tools"
                        image: "busybox"
                        command: "sleep"
                        args: "99d"

  serviceAccount:
    create: true

  rbac:
    create: true

  initializeOnce: true

  admin:
    username: admin
    password: admin123456

  installPlugins:
    - kubernetes
    - git
    - workflow-aggregator
    - docker-workflow
    - pipeline-stage-view
    - docker

persistence:
  enabled: true
  size: 10Gi
